package com.globalaffairs.handover.document;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.globalaffairs.handover.document.DocumentRequests.AttachmentInput;
import com.globalaffairs.handover.document.DocumentRequests.BundleInput;
import com.globalaffairs.handover.document.DocumentRequests.DecisionInput;
import com.globalaffairs.handover.document.DocumentRequests.EntryInput;
import com.globalaffairs.handover.document.DocumentRequests.FormattingInput;
import com.globalaffairs.handover.domain.HandoverSchema;
import com.globalaffairs.handover.domain.PropertyField;
import com.globalaffairs.handover.web.ApiException;
import com.globalaffairs.handover.web.Timestamps;
import java.time.Clock;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Transactional;

/**
 * Storing and advancing the handover document. Port of {@code app/api/handover/route.ts}.
 *
 * <p>The document is stored per account and always written whole: a save replaces the entries and
 * bundles rather than diffing them, which is what keeps the author's ordering and the client's
 * generated ids meaningful without a second identity scheme.
 */
@Service
public class DocumentService {

    static final String DRAFT = "draft";
    static final String PENDING = "pending";
    static final String REJECTED = "rejected";
    static final String APPROVED = "approved";

    /** Ids are generated by the client, never shown, and not part of the shared limits. */
    private static final int MAX_ID = 120;

    private static final TypeReference<Map<String, String>> PROPERTY_MAP = new TypeReference<>() {};
    private static final TypeReference<List<StoredAttachment>> ATTACHMENT_LIST = new TypeReference<>() {};
    private static final TypeReference<List<String>> ID_LIST = new TypeReference<>() {};

    private final HandoverDocumentRepository documents;
    private final HandoverEntryRowRepository entries;
    private final HandoverBundleRowRepository bundles;
    private final HandoverSchema schema;
    private final ObjectMapper objectMapper;
    private final Clock clock;

    public DocumentService(
            HandoverDocumentRepository documents,
            HandoverEntryRowRepository entries,
            HandoverBundleRowRepository bundles,
            HandoverSchema schema,
            ObjectMapper objectMapper,
            Clock clock) {
        this.documents = documents;
        this.entries = entries;
        this.bundles = bundles;
        this.schema = schema;
        this.objectMapper = objectMapper;
        this.clock = clock;
    }

    private HandoverSchema.DocumentLimits limits() {
        return schema.documentLimits();
    }

    /** A document is editable only before it is submitted, or after it comes back rejected. */
    static boolean isEditableStatus(String status) {
        return DRAFT.equals(status) || REJECTED.equals(status);
    }

    @Transactional(readOnly = true, isolation = Isolation.REPEATABLE_READ)
    public DocumentResponse find(String ownerEmail) {
        return documents.findById(ownerEmail).map(this::read).orElse(null);
    }

    /**
     * Every document that has been submitted at least once, for the part leader's list.
     *
     * <p>A draft is left out: it is nobody's submission yet. What is waiting comes first and in the
     * order it arrived, because that is the queue the reviewer works through; everything already
     * decided follows, most recent first, as a record to look back at.
     */
    @Transactional(readOnly = true)
    public List<DocumentSummary> findSubmitted() {
        List<HandoverDocument> submitted =
                documents.findByStatusInOrderByUpdatedAtDesc(List.of(PENDING, REJECTED, APPROVED));
        Stream<HandoverDocument> waiting = submitted.stream()
                .filter(document -> PENDING.equals(document.getStatus()))
                .sorted(Comparator.comparing(HandoverDocument::getUpdatedAt));
        Stream<HandoverDocument> decided =
                submitted.stream().filter(document -> !PENDING.equals(document.getStatus()));
        return Stream.concat(waiting, decided).map(DocumentService::summarise).toList();
    }

    private static DocumentSummary summarise(HandoverDocument document) {
        return new DocumentSummary(
                document.getOwnerEmail(),
                document.getOwnerName(),
                document.getStatus(),
                Timestamps.toIsoString(document.getUpdatedAt()),
                document.getSubmittedAt() == null ? null : Timestamps.toIsoString(document.getSubmittedAt()),
                document.getReviewedAt() == null ? null : Timestamps.toIsoString(document.getReviewedAt()),
                document.getReviewedBy());
    }

    public record DocumentSummary(
            String ownerEmail,
            String ownerName,
            String status,
            String updatedAt,
            String submittedAt,
            String reviewedAt,
            String reviewedBy) {}

    /**
     * Replaces the working document. A submitted document is frozen until the reviewer sends it
     * back, so this refuses rather than silently dropping the edit.
     */
    @Transactional
    public DocumentResponse save(String ownerEmail, String ownerName, DocumentRequests.SaveRequest request) {
        Optional<HandoverDocument> existing = documents.findById(ownerEmail);
        existing.ifPresent(document -> {
            if (!isEditableStatus(document.getStatus())) {
                throw ApiException.conflict(PENDING.equals(document.getStatus())
                        ? "검토 중인 문서는 수정할 수 없습니다."
                        : "승인된 문서는 수정할 수 없습니다.");
            }
        });

        DocumentRequests.SaveRequest body =
                request == null ? new DocumentRequests.SaveRequest(null, null) : request;
        List<DocumentResponse.Entry> parsedEntries = parseEntries(body.entries());
        List<DocumentResponse.Bundle> parsedBundles = parseBundles(body.bundles(), parsedEntries);
        if (existing.filter(document -> REJECTED.equals(document.getStatus())).isPresent()) {
            List<DocumentResponse.Entry> storedEntries = readEntries(ownerEmail);
            List<DocumentResponse.Bundle> storedBundles = readBundles(ownerEmail);
            requireApprovedContentUnchanged(parsedEntries, parsedBundles, storedEntries, storedBundles);
            parsedBundles = preserveReview(parsedBundles, storedBundles);
        }

        HandoverDocument document = existing.orElseGet(
                () -> new HandoverDocument(ownerEmail, ownerName, DRAFT, Instant.now(clock)));
        document.setUpdatedAt(Instant.now(clock));
        return write(document, parsedEntries, parsedBundles);
    }

    /** The author hands the document to their part leader. */
    @Transactional
    public DocumentResponse submit(String ownerEmail) {
        HandoverDocument document = documents.findById(ownerEmail)
                .orElseThrow(() -> ApiException.notFound("저장된 인수인계서가 없습니다."));
        if (!isEditableStatus(document.getStatus())) {
            throw ApiException.conflict("이미 제출된 문서입니다.");
        }

        List<DocumentResponse.Entry> storedEntries = readEntries(ownerEmail);
        List<DocumentResponse.Bundle> storedBundles = readBundles(ownerEmail);
        requireSubmittable(storedEntries, storedBundles);

        Instant now = Instant.now(clock);
        document.setStatus(PENDING);
        document.setUpdatedAt(now);
        document.setSubmittedAt(now);
        document.setReviewedAt(null);
        document.setReviewedBy(null);
        /* Approved units survive a correction round; only returned units go back to review, and the
         * rejection they are answering moves aside so the reviewer can still read it. */
        List<DocumentResponse.Bundle> cleared = storedBundles.stream()
                .map(bundle -> APPROVED.equals(bundle.decision())
                        ? new DocumentResponse.Bundle(
                                bundle.id(), bundle.title(), bundle.entryIds(), APPROVED, "", "")
                        : new DocumentResponse.Bundle(
                                bundle.id(),
                                bundle.title(),
                                bundle.entryIds(),
                                null,
                                "",
                                REJECTED.equals(bundle.decision()) ? bundle.comment() : bundle.previousComment()))
                .toList();
        return write(document, storedEntries, cleared);
    }

    /** Turns an approved document into the editable base for the next academic year. */
    @Transactional
    public DocumentResponse rollover(String ownerEmail) {
        HandoverDocument document = documents.findById(ownerEmail)
                .orElseThrow(() -> ApiException.notFound("갱신할 인수인계서가 없습니다."));
        /* A retry after the first successful transition is harmless and must not reset fresh edits. */
        if (isEditableStatus(document.getStatus())) {
            return read(document);
        }
        if (PENDING.equals(document.getStatus())) {
            throw ApiException.conflict("파트장 검토가 끝난 후 연간 업데이트를 시작할 수 있습니다.");
        }

        List<DocumentResponse.Bundle> cleared = readBundles(ownerEmail).stream()
                .map(bundle -> new DocumentResponse.Bundle(
                        bundle.id(), bundle.title(), bundle.entryIds(), null, "", ""))
                .toList();
        document.setStatus(DRAFT);
        document.setUpdatedAt(Instant.now(clock));
        document.setSubmittedAt(null);
        document.setReviewedAt(null);
        document.setReviewedBy(null);
        return write(document, readEntries(ownerEmail), cleared);
    }

    /** The part leader returns a verdict on every unit at once, so a review lands atomically. */
    @Transactional
    public DocumentResponse review(String ownerEmail, String reviewerName, List<DecisionInput> decisions) {
        HandoverDocument document = documents.findById(ownerEmail)
                .orElseThrow(() -> ApiException.notFound("검토할 인수인계서가 없습니다."));
        if (!PENDING.equals(document.getStatus())) {
            throw ApiException.conflict("검토 대기 중인 문서가 아닙니다.");
        }

        Map<String, DecisionInput> verdicts = parseDecisions(decisions);
        List<DocumentResponse.Bundle> storedBundles = readBundles(ownerEmail);
        Set<String> expectedBundleIds = storedBundles.stream()
                .filter(bundle -> !APPROVED.equals(bundle.decision()))
                .map(DocumentResponse.Bundle::id)
                .collect(Collectors.toSet());

        /* Older clients may echo an already-approved verdict. Accept that harmless echo, but never
         * let a later review overturn the approval. */
        storedBundles.stream()
                .filter(bundle -> APPROVED.equals(bundle.decision()))
                .forEach(bundle -> {
                    DecisionInput repeated = verdicts.remove(bundle.id());
                    if (repeated != null && !APPROVED.equals(repeated.decision())) {
                        throw ApiException.conflict("이미 승인된 담당업무 단위는 검토 결과를 변경할 수 없습니다.");
                    }
                });
        if (!verdicts.keySet().equals(expectedBundleIds)) {
            throw ApiException.badRequest("모든 담당업무 단위를 검토해야 합니다.");
        }

        List<DocumentResponse.Bundle> reviewed = storedBundles.stream()
                .map(bundle -> {
                    if (APPROVED.equals(bundle.decision())) {
                        return bundle;
                    }
                    DecisionInput verdict = verdicts.get(bundle.id());
                    String comment = REJECTED.equals(verdict.decision()) ? trimmed(verdict.comment()) : "";
                    /* the verdict answers whatever was outstanding, so the old request retires */
                    return new DocumentResponse.Bundle(
                            bundle.id(), bundle.title(), bundle.entryIds(), verdict.decision(), comment, "");
                })
                .toList();

        Instant now = Instant.now(clock);
        document.setStatus(
                reviewed.stream().anyMatch(bundle -> REJECTED.equals(bundle.decision())) ? REJECTED : APPROVED);
        document.setUpdatedAt(now);
        document.setReviewedAt(now);
        document.setReviewedBy(reviewerName);
        return write(document, readEntries(ownerEmail), reviewed);
    }

    /* ------------------------------------------------------------------ *
     * Reading
     * ------------------------------------------------------------------ */

    private DocumentResponse read(HandoverDocument document) {
        return compose(document, readEntries(document.getOwnerEmail()), readBundles(document.getOwnerEmail()));
    }

    private DocumentResponse compose(
            HandoverDocument document,
            List<DocumentResponse.Entry> entryList,
            List<DocumentResponse.Bundle> bundleList) {
        return new DocumentResponse(
                document.getOwnerName(),
                document.getStatus(),
                entryList,
                bundleList,
                Timestamps.toIsoString(document.getUpdatedAt()),
                document.getSubmittedAt() == null ? null : Timestamps.toIsoString(document.getSubmittedAt()),
                document.getReviewedAt() == null ? null : Timestamps.toIsoString(document.getReviewedAt()),
                document.getReviewedBy());
    }

    private List<DocumentResponse.Entry> readEntries(String ownerEmail) {
        return entries.findByOwnerEmailOrderByPositionAsc(ownerEmail).stream()
                .map(row -> new DocumentResponse.Entry(
                        row.getEntryId(),
                        row.getCategory(),
                        row.getTitle(),
                        row.getDetail(),
                        fromJson(row.getProperties(), PROPERTY_MAP),
                        fromJson(row.getAttachments(), ATTACHMENT_LIST).stream()
                                .map(file -> new DocumentResponse.Attachment(
                                        file.id(), file.name(), file.size(), file.type(), ""))
                                .toList(),
                        new DocumentResponse.Formatting(row.getFontFamily(), row.getFontSize())))
                .toList();
    }

    private List<DocumentResponse.Bundle> readBundles(String ownerEmail) {
        return bundles.findByOwnerEmailOrderByPositionAsc(ownerEmail).stream()
                .map(row -> new DocumentResponse.Bundle(
                        row.getBundleId(),
                        row.getTitle(),
                        fromJson(row.getEntryIds(), ID_LIST),
                        row.getDecision(),
                        row.getComment(),
                        row.getPreviousComment()))
                .toList();
    }

    /** A correction save keeps the previous verdict visible; resubmission clears it explicitly. */
    private static List<DocumentResponse.Bundle> preserveReview(
            List<DocumentResponse.Bundle> incoming, List<DocumentResponse.Bundle> stored) {
        Map<String, DocumentResponse.Bundle> previous = stored.stream()
                .collect(Collectors.toMap(DocumentResponse.Bundle::id, bundle -> bundle));
        return incoming.stream()
                .map(bundle -> {
                    DocumentResponse.Bundle verdict = previous.get(bundle.id());
                    return verdict == null
                            ? bundle
                            : new DocumentResponse.Bundle(
                                    bundle.id(),
                                    bundle.title(),
                                    bundle.entryIds(),
                                    verdict.decision(),
                                    verdict.comment(),
                                    verdict.previousComment());
                })
                .toList();
    }

    /** A returned document may change only the units the reviewer rejected. */
    private static void requireApprovedContentUnchanged(
            List<DocumentResponse.Entry> incomingEntries,
            List<DocumentResponse.Bundle> incomingBundles,
            List<DocumentResponse.Entry> storedEntries,
            List<DocumentResponse.Bundle> storedBundles) {
        Map<String, DocumentResponse.Entry> incomingEntryById = incomingEntries.stream()
                .collect(Collectors.toMap(DocumentResponse.Entry::id, entry -> entry));
        Map<String, DocumentResponse.Entry> storedEntryById = storedEntries.stream()
                .collect(Collectors.toMap(DocumentResponse.Entry::id, entry -> entry));
        Map<String, DocumentResponse.Bundle> incomingBundleById = incomingBundles.stream()
                .collect(Collectors.toMap(DocumentResponse.Bundle::id, bundle -> bundle));

        for (DocumentResponse.Bundle approved : storedBundles) {
            if (!APPROVED.equals(approved.decision())) {
                continue;
            }
            DocumentResponse.Bundle incoming = incomingBundleById.get(approved.id());
            if (incoming == null
                    || !approved.title().equals(incoming.title())
                    || !approved.entryIds().equals(incoming.entryIds())) {
                throw ApiException.conflict("승인된 담당업무 단위는 수정할 수 없습니다.");
            }
            for (String entryId : approved.entryIds()) {
                if (!storedEntryById.get(entryId).equals(incomingEntryById.get(entryId))) {
                    throw ApiException.conflict("승인된 담당업무 단위의 항목은 수정할 수 없습니다.");
                }
            }
        }
    }

    /* ------------------------------------------------------------------ *
     * Writing
     * ------------------------------------------------------------------ */

    private DocumentResponse write(
            HandoverDocument document,
            List<DocumentResponse.Entry> entryList,
            List<DocumentResponse.Bundle> bundleList) {
        String ownerEmail = document.getOwnerEmail();
        documents.save(document);

        /* the deletes have to reach the database before the inserts, or the unique keys collide */
        entries.deleteByOwnerEmail(ownerEmail);
        bundles.deleteByOwnerEmail(ownerEmail);
        entries.flush();
        bundles.flush();

        List<HandoverEntryRow> entryRows = new ArrayList<>();
        for (int position = 0; position < entryList.size(); position++) {
            DocumentResponse.Entry entry = entryList.get(position);
            entryRows.add(new HandoverEntryRow(
                    ownerEmail,
                    entry.id(),
                    position,
                    entry.category(),
                    entry.title(),
                    entry.detail(),
                    toJson(entry.properties()),
                    toJson(entry.attachments().stream()
                            .map(file -> new StoredAttachment(file.id(), file.name(), file.size(), file.type()))
                            .toList()),
                    entry.formatting().fontFamily(),
                    entry.formatting().fontSize()));
        }
        entries.saveAll(entryRows);

        List<HandoverBundleRow> bundleRows = new ArrayList<>();
        for (int position = 0; position < bundleList.size(); position++) {
            DocumentResponse.Bundle bundle = bundleList.get(position);
            bundleRows.add(new HandoverBundleRow(
                    ownerEmail,
                    bundle.id(),
                    position,
                    bundle.title(),
                    toJson(bundle.entryIds()),
                    bundle.decision(),
                    bundle.comment(),
                    bundle.previousComment()));
        }
        bundles.saveAll(bundleRows);

        return compose(document, entryList, bundleList);
    }

    /** What actually reaches the column: the object URL is deliberately not stored. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    private record StoredAttachment(String id, String name, long size, String type) {}

    /* ------------------------------------------------------------------ *
     * Validation
     *
     * The client blocks most of this already, but the client is not the boundary. These rules and
     * their messages match app/api/handover/route.ts one for one.
     * ------------------------------------------------------------------ */

    private List<DocumentResponse.Entry> parseEntries(List<EntryInput> input) {
        if (input == null) {
            throw ApiException.badRequest("항목 목록을 보내주세요.");
        }
        if (input.size() > limits().entries()) {
            throw ApiException.badRequest("항목은 %d개까지 저장할 수 있습니다.".formatted(limits().entries()));
        }

        Set<String> seen = new HashSet<>();
        List<DocumentResponse.Entry> parsed = new ArrayList<>();
        for (EntryInput entry : input) {
            if (entry == null) {
                throw ApiException.badRequest("항목 목록을 보내주세요.");
            }
            String id = text(entry.id(), "항목 id", MAX_ID, true);
            if (!seen.add(id)) {
                throw ApiException.badRequest("항목 id가 중복되었습니다.");
            }
            if (!schema.isCategory(entry.category())) {
                throw ApiException.badRequest("알 수 없는 섹션입니다.");
            }
            FormattingInput formatting =
                    entry.formatting() == null ? new FormattingInput(null, null) : entry.formatting();
            parsed.add(new DocumentResponse.Entry(
                    id,
                    entry.category(),
                    text(entry.title(), "문서 제목", limits().entryTitle(), true),
                    text(entry.detail(), "본문", limits().entryDetail(), true),
                    parseProperties(entry.properties(), entry.category()),
                    parseAttachments(entry.attachments()),
                    new DocumentResponse.Formatting(
                            orDefault(text(formatting.fontFamily(), "글꼴", 80, false), "Pretendard"),
                            orDefault(text(formatting.fontSize(), "글자 크기", 4, false), "16"))));
        }
        return parsed;
    }

    /** Property keys are fixed per category, so anything unrecognised is dropped rather than stored. */
    private Map<String, String> parseProperties(Map<String, String> input, String category) {
        Map<String, String> properties = new LinkedHashMap<>();
        if (input == null) {
            return properties;
        }
        Set<String> known = new LinkedHashSet<>(schema.propertyFields(category).stream()
                .map(PropertyField::key)
                .toList());
        input.forEach((key, value) -> {
            if (!known.contains(key) || value == null || value.isEmpty()) {
                return;
            }
            String cleaned = text(value, "%s 속성".formatted(key), limits().propertyValue(), false);
            if (!cleaned.isEmpty()) {
                properties.put(key, cleaned);
            }
        });
        return properties;
    }

    private List<DocumentResponse.Attachment> parseAttachments(List<AttachmentInput> input) {
        if (input == null) {
            return List.of();
        }
        if (input.size() > limits().attachmentsPerEntry()) {
            throw ApiException.badRequest(
                    "첨부파일은 항목당 %d개까지 저장할 수 있습니다.".formatted(limits().attachmentsPerEntry()));
        }
        return input.stream()
                .map(file -> {
                    if (file == null || file.size() == null || file.size() < 0) {
                        throw ApiException.badRequest("첨부파일 크기가 올바르지 않습니다.");
                    }
                    if (file.size() > limits().attachmentBytes()) {
                        throw ApiException.badRequest("첨부파일은 파일당 %s까지 저장할 수 있습니다."
                                .formatted(formatBytes(limits().attachmentBytes())));
                    }
                    return new DocumentResponse.Attachment(
                            text(file.id(), "첨부파일 id", MAX_ID, true),
                            text(file.name(), "첨부파일 이름", limits().attachmentName(), true),
                            file.size(),
                            text(file.type(), "첨부파일 형식", 200, false),
                            "");
                })
                .toList();
    }

    private List<DocumentResponse.Bundle> parseBundles(
            List<BundleInput> input, List<DocumentResponse.Entry> parsedEntries) {
        if (input == null) {
            throw ApiException.badRequest("업무 단위 목록을 보내주세요.");
        }
        if (input.size() > limits().bundles()) {
            throw ApiException.badRequest("업무 단위는 %d개까지 만들 수 있습니다.".formatted(limits().bundles()));
        }

        Set<String> entryIds = parsedEntries.stream()
                .map(DocumentResponse.Entry::id)
                .collect(Collectors.toCollection(LinkedHashSet::new));
        Set<String> seenBundles = new HashSet<>();
        Set<String> assigned = new HashSet<>();

        List<DocumentResponse.Bundle> parsed = new ArrayList<>();
        for (BundleInput bundle : input) {
            if (bundle == null || bundle.entryIds() == null) {
                throw ApiException.badRequest("업무 단위에 연결된 항목 목록이 필요합니다.");
            }
            String id = text(bundle.id(), "업무 단위 id", MAX_ID, true);
            if (!seenBundles.add(id)) {
                throw ApiException.badRequest("업무 단위 id가 중복되었습니다.");
            }
            List<String> linked = new ArrayList<>();
            for (String candidate : bundle.entryIds()) {
                String entryId = text(candidate, "연결 항목 id", MAX_ID, true);
                if (!entryIds.contains(entryId)) {
                    throw ApiException.badRequest("존재하지 않는 항목이 업무 단위에 연결되어 있습니다.");
                }
                if (!assigned.add(entryId)) {
                    throw ApiException.badRequest("한 항목을 여러 업무 단위에 배치할 수 없습니다.");
                }
                linked.add(entryId);
            }
            /* an unnamed unit is legal while drafting; submission is where the name becomes required */
            parsed.add(new DocumentResponse.Bundle(
                    id, text(bundle.title(), "업무 단위 이름", limits().bundleTitle(), false), linked, null, "", ""));
        }
        return parsed;
    }

    private void requireSubmittable(
            List<DocumentResponse.Entry> entryList, List<DocumentResponse.Bundle> bundleList) {
        if (entryList.isEmpty()) {
            throw ApiException.badRequest("작성된 항목이 없습니다.");
        }
        if (bundleList.isEmpty()) {
            throw ApiException.badRequest("담당업무 단위를 하나 이상 만들어 주세요.");
        }
        if (bundleList.stream().anyMatch(bundle -> bundle.title().isBlank())) {
            throw ApiException.badRequest("이름이 비어 있는 담당업무 단위가 있습니다.");
        }
        if (bundleList.stream().anyMatch(bundle -> bundle.entryIds().isEmpty())) {
            throw ApiException.badRequest("항목이 없는 담당업무 단위가 있습니다.");
        }
        Set<String> assigned = bundleList.stream()
                .flatMap(bundle -> bundle.entryIds().stream())
                .collect(Collectors.toSet());
        if (entryList.stream().anyMatch(entry -> !assigned.contains(entry.id()))) {
            throw ApiException.badRequest("모든 항목을 담당업무 단위에 배치해야 제출할 수 있습니다.");
        }
    }

    private Map<String, DecisionInput> parseDecisions(List<DecisionInput> decisions) {
        if (decisions == null) {
            throw ApiException.badRequest("검토 결과를 보내주세요.");
        }
        Map<String, DecisionInput> verdicts = new LinkedHashMap<>();
        for (DecisionInput raw : decisions) {
            if (raw == null
                    || (!APPROVED.equals(raw.decision()) && !REJECTED.equals(raw.decision()))) {
                throw ApiException.badRequest("승인 또는 반려 중 하나를 선택해 주세요.");
            }
            String comment = text(raw.comment(), "검토 의견", limits().comment(), false);
            if (REJECTED.equals(raw.decision()) && comment.isEmpty()) {
                throw ApiException.badRequest("반려한 업무 단위에는 보완 요청 코멘트가 필요합니다.");
            }
            String bundleId = text(raw.bundleId(), "업무 단위 id", MAX_ID, true);
            if (verdicts.put(bundleId, new DecisionInput(bundleId, raw.decision(), comment)) != null) {
                throw ApiException.badRequest("같은 업무 단위의 검토 결과가 중복되었습니다.");
            }
        }
        return verdicts;
    }

    private static String formatBytes(long bytes) {
        if (bytes % (1024 * 1024) == 0) {
            return "%dMB".formatted(bytes / (1024 * 1024));
        }
        return "%d바이트".formatted(bytes);
    }

    private static String text(String value, String field, int max, boolean required) {
        if (value == null) {
            if (required) {
                throw ApiException.badRequest("%s을(를) 입력해 주세요.".formatted(field));
            }
            return "";
        }
        String trimmed = value.trim();
        if (required && trimmed.isEmpty()) {
            throw ApiException.badRequest("%s을(를) 입력해 주세요.".formatted(field));
        }
        if (trimmed.length() > max) {
            throw ApiException.badRequest("%s은(는) %d자 이내로 입력해 주세요.".formatted(field, max));
        }
        return trimmed;
    }

    private static String trimmed(String value) {
        return value == null ? "" : value.trim();
    }

    private static String orDefault(String value, String fallback) {
        return value == null || value.isEmpty() ? fallback : value;
    }

    private String toJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException failure) {
            throw new IllegalStateException("could not serialise handover document field", failure);
        }
    }

    private <T> T fromJson(String value, TypeReference<T> type) {
        try {
            return objectMapper.readValue(value, type);
        } catch (JsonProcessingException failure) {
            throw new IllegalStateException("stored handover document field is not readable JSON", failure);
        }
    }
}
