-- One approved handover document, kept as the record of the academic year it closed.
--
-- `handover_documents` holds exactly one row per account and the annual rollover rewrites it in
-- place, so until now approving a document and then starting next year's erased the year that was
-- just approved. This table is where that year goes: written once, when the part leader's verdict
-- is 승인, and never edited afterwards.
--
-- The document itself is stored as the same JSON the API already answers with rather than as a
-- second set of entry and bundle tables. An archive is only ever read whole and never queried
-- into, and freezing the serialised shape is what keeps a 2026 record readable after the live
-- schema moves on. The columns beside it are the ones the year list shows without opening anything.
CREATE TABLE IF NOT EXISTS handover_archives (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY,
    owner_email   text        NOT NULL,
    owner_name    text        NOT NULL,
    academic_year integer     NOT NULL,
    status        text        NOT NULL,
    document      text        NOT NULL,
    entry_count   integer     NOT NULL,
    bundle_count  integer     NOT NULL,
    submitted_at  timestamptz,
    reviewed_at   timestamptz,
    reviewed_by   text,
    archived_at   timestamptz NOT NULL,
    CONSTRAINT handover_archives_pkey PRIMARY KEY (id),
    -- One record per author per academic year. A correction round that is approved a second time
    -- inside the same year replaces the record rather than adding a second one.
    CONSTRAINT handover_archives_owner_year_key UNIQUE (owner_email, academic_year),
    CONSTRAINT handover_archives_status_check CHECK (status IN ('approved')),
    CONSTRAINT handover_archives_year_check CHECK (academic_year BETWEEN 2000 AND 2100),
    CONSTRAINT handover_archives_counts_check CHECK (entry_count >= 0 AND bundle_count >= 0)
);

-- Deliberately no foreign key to handover_documents: the record of a year has to outlive whatever
-- happens to the live row, including an account that leaves the office.

-- An author opening their own past years.
CREATE INDEX IF NOT EXISTS handover_archives_owner_idx
    ON handover_archives (owner_email, academic_year DESC);

-- The part leader reading a whole year across the office.
CREATE INDEX IF NOT EXISTS handover_archives_year_idx
    ON handover_archives (academic_year DESC, owner_name);

COMMENT ON TABLE handover_archives IS
    'one approved handover document per author per academic year, frozen as the year''s record';
COMMENT ON COLUMN handover_archives.document IS
    'the document as /api/handover answers it, serialised whole and never edited afterwards';
