-- Append-only trail of task schedule changes; the latest row for a task_key wins.
-- Ported from drizzle/0001_task_reschedules.sql (Cloudflare D1 / SQLite).
--   id INTEGER PRIMARY KEY AUTOINCREMENT -> bigint GENERATED BY DEFAULT AS IDENTITY.
--   "BY DEFAULT" rather than "ALWAYS" so an import of the D1 export can keep the original ids, which
--   carry the ordering the application depends on. Reset the sequence after such an import; see
--   backend/docs/MIGRATION-FROM-D1.md.
--   changed_at TEXT NOT NULL -> timestamptz; it is serialised back to the same ISO-8601 string
--   (UTC, milliseconds) the frontend already receives.
CREATE TABLE IF NOT EXISTS task_reschedules (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY,
    task_key   text        NOT NULL,
    person_id  text        NOT NULL,
    task_title text        NOT NULL,
    from_start integer     NOT NULL,
    to_start   integer     NOT NULL,
    reason     text        NOT NULL,
    changed_by text        NOT NULL,
    changed_at timestamptz NOT NULL,
    CONSTRAINT task_reschedules_pkey PRIMARY KEY (id)
);

-- Serves both "the whole trail in order" and "the latest row for one task".
CREATE INDEX IF NOT EXISTS task_reschedules_task_key_idx ON task_reschedules (task_key, id);

-- Serves the per-person lookups the draft and calendar-check endpoints make.
CREATE INDEX IF NOT EXISTS task_reschedules_person_id_idx ON task_reschedules (person_id, id);

COMMENT ON TABLE task_reschedules IS 'append-only reschedule history; the highest id per task_key is the current start week';
