-- The saved handover document: workflow state, the author's entries, and the units they grouped
-- them into. Ported from drizzle/0002_handover_documents.sql (Cloudflare D1 / SQLite).
--   TEXT timestamps -> timestamptz; serialised back to the same ISO-8601 string (UTC, milliseconds)
--   the frontend already receives, exactly as V2 does for task_reschedules.
--   The child tables carry a surrogate identity key instead of D1's (owner_email, entry_id)
--   composite primary key. The uniqueness that mattered is kept as a constraint below; a single
--   column key is what lets JPA map these without an @IdClass. The API contract is the JSON, not
--   the DDL, so the two backends still answer identically.
CREATE TABLE IF NOT EXISTS handover_documents (
    owner_email  text        NOT NULL,
    owner_name   text        NOT NULL,
    status       text        NOT NULL,
    updated_at   timestamptz NOT NULL,
    submitted_at timestamptz,
    reviewed_at  timestamptz,
    reviewed_by  text,
    version      bigint      NOT NULL DEFAULT 0,
    CONSTRAINT handover_documents_pkey PRIMARY KEY (owner_email),
    CONSTRAINT handover_documents_status_check
        CHECK (status IN ('draft', 'pending', 'rejected', 'approved'))
);

-- Entries and bundles are always written as one whole document, so `position` is the only thing
-- carrying the order the author arranged them in.
CREATE TABLE IF NOT EXISTS handover_entries (
    id          bigint  GENERATED BY DEFAULT AS IDENTITY,
    owner_email text    NOT NULL,
    entry_id    text    NOT NULL,
    position    integer NOT NULL,
    category    text    NOT NULL,
    title       text    NOT NULL,
    detail      text    NOT NULL,
    -- JSON held as text rather than jsonb: these are read and written whole, never queried into,
    -- and text keeps the column identical in meaning to the D1 one it was ported from.
    properties  text    NOT NULL,
    attachments text    NOT NULL,
    font_family text    NOT NULL,
    font_size   text    NOT NULL,
    CONSTRAINT handover_entries_pkey PRIMARY KEY (id),
    CONSTRAINT handover_entries_owner_entry_key UNIQUE (owner_email, entry_id),
    CONSTRAINT handover_entries_owner_position_key UNIQUE (owner_email, position),
    CONSTRAINT handover_entries_position_check CHECK (position >= 0),
    CONSTRAINT handover_entries_owner_fkey
        FOREIGN KEY (owner_email) REFERENCES handover_documents (owner_email) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS handover_bundles (
    id          bigint  GENERATED BY DEFAULT AS IDENTITY,
    owner_email text    NOT NULL,
    bundle_id   text    NOT NULL,
    position    integer NOT NULL,
    title       text    NOT NULL,
    entry_ids   text    NOT NULL,
    decision    text,
    comment     text    NOT NULL,
    CONSTRAINT handover_bundles_pkey PRIMARY KEY (id),
    CONSTRAINT handover_bundles_owner_bundle_key UNIQUE (owner_email, bundle_id),
    CONSTRAINT handover_bundles_owner_position_key UNIQUE (owner_email, position),
    CONSTRAINT handover_bundles_position_check CHECK (position >= 0),
    CONSTRAINT handover_bundles_owner_fkey
        FOREIGN KEY (owner_email) REFERENCES handover_documents (owner_email) ON DELETE CASCADE,
    CONSTRAINT handover_bundles_decision_check
        CHECK (decision IS NULL OR decision IN ('pending', 'approved', 'rejected'))
);

-- Every read is "one owner's rows in author order".
CREATE INDEX IF NOT EXISTS handover_entries_owner_idx ON handover_entries (owner_email, position);
CREATE INDEX IF NOT EXISTS handover_bundles_owner_idx ON handover_bundles (owner_email, position);

-- Serves a part leader looking for what is waiting on them.
CREATE INDEX IF NOT EXISTS handover_documents_status_idx ON handover_documents (status, updated_at);

COMMENT ON TABLE handover_documents IS 'one saved handover document per account, keyed by owner email';
