CREATE TABLE IF NOT EXISTS task_checklist_items (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY,
    task_key   text        NOT NULL,
    person_id  text        NOT NULL,
    task_title text        NOT NULL,
    item_key   text        NOT NULL,
    completed  boolean     NOT NULL DEFAULT false,
    updated_by text        NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT task_checklist_items_pkey PRIMARY KEY (id),
    CONSTRAINT task_checklist_items_task_item_key UNIQUE (task_key, item_key),
    CONSTRAINT task_checklist_items_item_key_check CHECK (
        item_key IN ('result-report', 'schedule-share', 'contact-refresh')
    )
);

COMMENT ON TABLE task_checklist_items IS 'durable handover checklist state for one calendar task';
