CREATE TABLE IF NOT EXISTS custom_tasks (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY,
    person_id  text        NOT NULL,
    title      text        NOT NULL,
    start_week integer     NOT NULL,
    duration   integer     NOT NULL,
    note       text        NOT NULL,
    created_by text        NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT custom_tasks_pkey PRIMARY KEY (id),
    CONSTRAINT custom_tasks_person_title_key UNIQUE (person_id, title),
    CONSTRAINT custom_tasks_start_week_check CHECK (start_week >= 0 AND start_week < 48),
    CONSTRAINT custom_tasks_duration_check CHECK (duration >= 1 AND duration <= 48),
    CONSTRAINT custom_tasks_period_check CHECK (start_week + duration <= 48)
);

CREATE INDEX IF NOT EXISTS custom_tasks_person_id_idx
    ON custom_tasks (person_id, start_week, id);

COMMENT ON TABLE custom_tasks IS 'calendar tasks created from the workspace';
