package com.globalaffairs.handover.db;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.globalaffairs.handover.member.RemovedMember;
import com.globalaffairs.handover.member.RemovedMemberRepository;
import com.globalaffairs.handover.schedule.TaskReschedule;
import com.globalaffairs.handover.schedule.TaskRescheduleRepository;
import java.time.Instant;
import java.util.List;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * Runs the Flyway migrations against a real PostgreSQL and checks the schema they produce is the one
 * the entities are mapped against — including the identity column that replaced SQLite's
 * {@code AUTOINCREMENT}.
 *
 * <p>Needs a working Docker daemon. Without one the whole class is skipped rather than failed, so a
 * machine with no Docker can still run the rest of the suite; see the README.
 */
@SpringBootTest
@Testcontainers
@EnabledIf("dockerAvailable")
class FlywayMigrationTest {

    @Container
    @SuppressWarnings("resource")
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16-alpine")
            .withDatabaseName("handover")
            .withUsername("handover")
            .withPassword("handover");

    static boolean dockerAvailable() {
        try {
            return org.testcontainers.DockerClientFactory.instance().isDockerAvailable();
        } catch (RuntimeException unavailable) {
            return false;
        }
    }

    @DynamicPropertySource
    static void datasource(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
        registry.add("spring.datasource.username", POSTGRES::getUsername);
        registry.add("spring.datasource.password", POSTGRES::getPassword);
    }

    @Autowired
    private DataSource dataSource;

    @Autowired
    private RemovedMemberRepository removedMembers;

    @Autowired
    private TaskRescheduleRepository reschedules;

    @Test
    void appliesEveryMigrationOnce() {
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        List<String> applied = jdbc.queryForList(
                "SELECT script FROM flyway_schema_history WHERE success ORDER BY installed_rank", String.class);

        assertThat(applied).containsExactly("V1__removed_members.sql", "V2__task_reschedules.sql");
    }

    @Test
    void createsBothTablesWithTheIndexesTheQueriesRelyOn() {
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);

        assertThat(jdbc.queryForList(
                        "SELECT tablename FROM pg_tables WHERE schemaname = 'public'", String.class))
                .contains("removed_members", "task_reschedules");
        assertThat(jdbc.queryForList(
                        "SELECT indexname FROM pg_indexes WHERE tablename = 'task_reschedules'", String.class))
                .contains("task_reschedules_pkey", "task_reschedules_task_key_idx", "task_reschedules_person_id_idx");
    }

    @Test
    void generatesIdsWithoutOneBeingSuppliedTheWayAutoincrementDid() {
        TaskReschedule first = reschedules.save(new TaskReschedule(
                "minseo::비자 연장 집중기간", "minseo", "비자 연장 집중기간",
                21, 23, "사유", "박민서", Instant.parse("2026-08-29T01:02:03.456Z")));
        TaskReschedule second = reschedules.save(new TaskReschedule(
                "minseo::비자 연장 집중기간", "minseo", "비자 연장 집중기간",
                23, 25, "사유", "박민서", Instant.parse("2026-08-29T01:02:04.456Z")));

        assertThat(first.getId()).isNotNull();
        assertThat(second.getId()).isGreaterThan(first.getId());
        assertThat(reschedules.findFirstByTaskKeyOrderByIdDesc("minseo::비자 연장 집중기간"))
                .get()
                .extracting(TaskReschedule::getToStart)
                .isEqualTo(25);
    }

    @Test
    void acceptsAnExplicitIdSoAD1ImportCanKeepItsOwnOrdering() {
        /* GENERATED BY DEFAULT, not ALWAYS: the import in docs/MIGRATION-FROM-D1.md depends on this. */
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.update("""
                INSERT INTO task_reschedules
                  (id, task_key, person_id, task_title, from_start, to_start, reason, changed_by, changed_at)
                VALUES (9001, 'jiwoo::상반기 정기상담', 'jiwoo', '상반기 정기상담', 8, 10, '가져온 기록', '최지우', now())
                """);

        assertThat(jdbc.queryForObject(
                        "SELECT reason FROM task_reschedules WHERE id = 9001", String.class))
                .isEqualTo("가져온 기록");
    }

    @Test
    void roundTripsATimestampWithoutLosingTheMillisecondsTheFrontendSees() {
        Instant changedAt = Instant.parse("2026-08-29T01:02:03.456Z");
        TaskReschedule saved = reschedules.save(new TaskReschedule(
                "dohyun::외국인 장학 선발", "dohyun", "외국인 장학 선발", 4, 6, "사유", "이도현", changedAt));

        assertThat(reschedules.findById(saved.getId()))
                .get()
                .extracting(TaskReschedule::getChangedAt)
                .isEqualTo(changedAt);
    }

    @Test
    void keepsPersonIdUniqueInRemovedMembers() {
        removedMembers.save(new RemovedMember("nayeon", Instant.now()));

        assertThatThrownBy(() -> new JdbcTemplate(dataSource).update(
                        "INSERT INTO removed_members (person_id, removed_at) VALUES ('nayeon', now())"))
                .isInstanceOf(DataIntegrityViolationException.class);
    }
}
